[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "x64-build-config.json"

# Applies to all targets that have set the "os" field of their target configuration file to "none"
[target.'cfg(target_os = "none")']
runner = "bootimage runner"
